config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}          
  #all the ROUTES for User model, for Authentication/log in/register etc...

  resources :portfolios, except: [:show]

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'      #localhost:3000 will navigate to controller pages#home method and controller
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies           #we added has_many that means his childrens are :technologies

    accepts_nested_attributes_for :technologies, reject_if: lambda { |atte| atte['name'].blank? }

    include Placeholder #include Placeholder module that will share to class and instances some functionality

    validates_presence_of :title, :body #, :main_image, :thumb_image

    def self.angular
        where(subtitle: 'Angular')
    end

    scope :ruby_on_rails_port, -> {  where(subtitle: 'Ruby on Rails') }

    after_initialize :set_defaults    #after new is invoked, .self point to that new object, instance of Portfolio class/modal
    def set_defaults
        self.main_image ||= Placeholder.image_generator(height:'600', width:'400')
        self.thumb_image ||= Placeholder.image_generator(height:'350', width:'200')
    end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]  # before_action(arg, arg, arg)
  layout "portfolio" # same as ===> layout("portfolio")
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edite]}, site_admin: :all


    def index
        @portfolio_items = Portfolio.all   # Portfolio.find_by_sql("SELECT portfolios.* from portfolios")
         #Portfolio.all  #call instance on Portfolio class(modal) and put with .all method all hashes in array
    end

    def angular
      @angular_portfolio_items = Portfolio.angular
    end




    def new
        @portfolio_item = Portfolio.new #database method to return new Array with hashes with emtpy values new port object
        3.times { @portfolio_item.technologies.build } #make 3 instance of tech portfolio
    end


    def create
       @portfolio_item = Portfolio.new( portfolio_params )

        respond_to do |format|
          if @portfolio_item.save
    
            format.html { redirect_to portfolios_path, notice: 'PORTFOLIO was created! bravo!!' }
          else
            format.html { render :new}
          end
        end
      end




      def edit    #route will navigate to 2/edit and pass control to edit method which will interact with edith.html.erb view
        @show_param = params                         
        #@portfolio_item = Portfolio.find(params[:id]) #pass id prop form Portfolio instance object/hash {}
        #3.times { @portfolio_item.technologies.build } #make 3 instance of tech portfolio

      end


      #update method will be fired after we click update portfolio in edit.html page, which will activate this controller method
      def update
        #@portfolio_item = Portfolio.find(params[:id])
        respond_to do |format|
          if @portfolio_item.update( portfolio_params)
            format.html { redirect_to portfolios_path, notice: 'Portfolio record was updated!' }
          else
            format.html { render :edit }
          end
        end
      end



    def show #controller, interact with modal and view MVC pattern
        @show_param_1 = params
        #@portfolio_item = Portfolio.find(params[:id])        
    end


    def destroy
        #perform a lookup for specific record
        #@portfolio_item = Portfolio.find(params[:id])

        #destroy the record from database
        @portfolio_item.destroy

        #redirect
        respond_to do |format|
          format.html { redirect_to portfolios_url, notice: 'Record was removed!.' }
        end
    end

    
    private

    def portfolio_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body, 
                                        technologies_attributes: [:name]
                                       )
    end


    def set_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
    end


end






#id here will be took from URL we specified in browser
#Portfolio.all add .all method on this class object, or modal.
#first index method/action is for to list all of items from db/recors to the user, so, to the VIEW pattern from MVC
#these methods are all built in in Rails. so index/create/delete/add etc update...
#so i guess Portfolio class that also extends from someone, with .new will add us new instance object, to use to fill
#form submit part will call the BUILT IN  dev create end method here and pasas arguments we filled in form, to it


#params.require(:portfolio).permit(:title, :subtitle, :body) -for update

# params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]) =. for create

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<h1>Create a new Portfolio item</h1>

<h2>
<p>THese ar self default values for this record, images main and thumb:</p>
<%= @portfolio_item.main_image %>
<br>
<%= @portfolio_item.thumb_image %>
</h2>


<%= form_with(model: @portfolio_item, local: true) do |form| %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
  <%= form.fields_for :technologies do |technology_form| %>
    
  <li>
      <%= technology_form.label :name %>   
      <%= technology_form.text_field :name %>
  </li>
  <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>


  
<% end %>



<!-- so here, we take instance variable, filled with new Portfolio class instance, 
#@portfolio_item here is just an  Array with hashes with values of hashes of nil here, empty!
so we are saying, take each of Array elements, so take EACH HASH OBJECT with empty value
portfolio_item ARRAY OF EMPYY VALUE HASHE OBJECTS 

#text_field and text_area
-->

app/views/portfolios/_portfolio_item.html.erb
<h1 style=color:darkred> <%= link_to portfolio_item['title'], portfolio_show_path(portfolio_item['id'])  %> </h1>
<h3> <%=  portfolio_item['subtitle']  %> </h3>
<h5> <%=  portfolio_item['body']  %> </h5>
<p> <mark> <%= image_tag  portfolio_item['thumb_image'] unless portfolio_item['thumb_image'].nil?  %> </mark> </p>
<%= link_to "Edit!!", edit_portfolio_path(portfolio_item['id']) if logged_in?(:site_admin) %>
<%= link_to 'Delete Portfolio portfolio_item', portfolio_path(portfolio_item['id']), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)
 %>



<!--
<% 
 portfolio_item_i, len, id = portfolio_item['title'], portfolio_item['title']['length'], portfolio_item['id']
 img = portfolio_item['thumb_image']
%>
-->

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio items [ANGULAR] </h1>


<% @angular_portfolio_items.each do |item| %>

<% 
#define some pre variables to short code down
 item_i, len, id = item['title'], item['title']['length'], item['id']
 img = item['thumb_image']
%>



<h1 style=color:darkred> <%= link_to item_i, portfolio_show_path(id)  %>   </h1>
<h3> <%=  item['subtitle']  %> </h3>
<h5> <%=  item['body']  %> </h5>
<p> <mark> <%= image_tag  img unless img.nil?  %> </mark> </p>
<%= link_to "Edit!!", edit_portfolio_path(id) if logged_in?(:site_admin) %>
<%= link_to 'Delete Portfolio item', portfolio_path(id), method: :delete, data: { confirm: 'Are you sure?' }  if logged_in?(:site_admin) %>

<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit a Portfolio item</h1>

<%=  render("form", portfolio_item: @portfolio_item)      %>

app/views/portfolios/index.html.erb
<h1>Portfolio</h1>

<%= link_to "create new PORTFOLIO item", new_portfolio_url if logged_in?(:site_admin) %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %> <!-- manual collection with render to iterate-->






<!-- embeded ruby  <%%> this will work ruby code but not show it on the page this: <%=%> WILL SHOW IT-->

app/views/portfolios/new.html.erb
<%=  render("form", portfolio_item: @portfolio_item)      %>

app/views/portfolios/show.html.erb
<h1>Show that record</h1>

<% item, img = @portfolio_item, @portfolio_item['main_image']

%>

<%= image_tag img unless img.nil?  %>
<h1> <%= item['title'] %>  </h1>
<em><%= item.subtitle %></em>
<p><%=  item.body %></p>


<p>Portfolios usedd:</p>

<%= @portfolio_item.inspect%>


<% @portfolio_item.technologies.each do |t| %>

<p><%=  t.name
    #byebug
%> </p>


<% end %>



<p><%=  @show_param_1.inspect %></p>

<p><%=  Portfolio.new.inspect %></p>

<p><%=  Portfolio.inspect %></p>

<p><%=  Portfolio.angular.inspect    %></p>
<p><%=  Portfolio.where(subtitle: 'Angular').inspect %></p>
<p><%=  session[:source] %></p>


<p><%=  params.require(:id).inspect %></p>